[project]
  name            = "timeclock_entry_processor"
  version         = "1.10.3"
  description     = "Add your description here"
  requires-python = ">=3.14"
  dependencies    = [
    "aeth-ext>=3.3.5",
    "aiologic>=0.16.0",
    "fpdf2>=2.8.7",
    "pandas[performance]>=3.0.2",
    "pydantic-settings>=2.14.2",
    "python-dateutil>=2.9.0",
    "rich>=15.0.0",
    "typer>=0.26.0",
    "tzdata>=2025.3",
    "uvloop>=0.22.1 ; sys_platform == 'linux'",
    "winloop>=0.6.0 ; sys_platform == 'win32'",
  ]

  [project.scripts]
    timeclock-entry-processor = "timeclock_entry_processor.__main__:app"

[dependency-groups]
  dev = [
    "pandas-stubs>=3.0.0",
    "poe-tasks>=4.0.1",
    "poethepoet>=0.46.0",
    "types-python-dateutil>=2.9.0",
  ]

[build-system]
  requires      = ["uv_build>=0.11.2,<0.12.0"]
  build-backend = "uv_build"

[tool.coverage.run]
  data_file   = ".cache/.coverage"
  source_pkgs = ["aeth_ext"]

[tool.coverage.report]
  show_missing = true

[tool.docker]
  # Paths relative to /app that the entrypoint will chown to nonroot:nonroot.
  # Typically these are directories that will be bind-mounted as Docker volumes.
  chown_paths = [
    "persisted_data",
  ]
  # Paths relative to /app that the entrypoint will create (mkdir -p) and chown.
  # These are implicitly included in the chown step.
  mkdirs      = []

[tool.poe]
  include_script = [{ script = "poe_tasks:tasks", executor = { type = "uv", frozen = true } }]

[tool.pyright]
  extends = "../pyproject.toml"

[tool.pytest.ini_options]
  addopts      = [
    "--cov",
    "--cov-report=term-missing",
    "--strict-markers",
    "--strict-config",
    "-ra"
  ]
  cache_dir    = ".cache/pytest"
  testpaths    = ["tests"]
  xfail_strict = true
  asyncio_mode = "auto"

[tool.ruff]
  extend    = "../pyproject.toml"
  cache-dir = ".cache/ruff"

  src = ["./src"]

[tool.uv]
  environments = [
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
  ]

  [tool.uv.sources]
    aeth-ext  = [
      { index = "SFTPyPI", marker = "sys_platform == 'linux'" },
      { path = "../aeth_ext", editable = true, marker = "sys_platform == 'win32'" },
    ]
    poe-tasks = [
      { index = "SFTPyPI" },
      # , marker = "sys_platform == 'linux'"
      # { path = "../poe_tasks", editable = true, marker = "sys_platform == 'win32'" },
    ]

  [[tool.uv.index]]
    name        = "SFTPyPI"
    url         = "https://pypi.sweetfiretobacco.com/jacob.ogden/internal/+simple"
    publish-url = "https://pypi.sweetfiretobacco.com/jacob.ogden/internal/"
    explicit    = true
