[project]
  name            = "timeclock_entry_processor"
  version         = "1.9.0"
  description     = "Add your description here"
  readme          = "README.md"
  requires-python = ">=3.14"
  dependencies    = [
    "aeth-ext>=3.3.5",
    "aiologic>=0.16.0",
    "fpdf2>=2.8.7",
    "pandas[performance]>=3.0.2",
    "pydantic-settings>=2.14.2",
    "python-dateutil>=2.9.0",
    "rich>=15.0.0",
    "typer>=0.26.0",
    "tzdata>=2025.3",
    "uvloop>=0.22.1 ; sys_platform == 'linux'",
    "winloop>=0.6.0 ; sys_platform == 'win32'",
  ]

[dependency-groups]
  dev = [
    "pandas-stubs>=3.0.0",
    "poe-tasks>=4.0.1",
    "poethepoet>=0.46.0",
    "types-python-dateutil>=2.9.0",
  ]

[tool.poe]
  include_script = "poe_tasks:tasks"

[tool.pyright]
  extends = "../pyproject.toml"

[tool.ruff]
  extend = "../pyproject.toml"

  src = ["./src"]

[tool.uv]
  environments = [
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
  ]

  [tool.uv.sources]
    aeth-ext  = [
      { index = "SFTPyPI", marker = "sys_platform == 'linux'" },
      { path = "../aeth_ext", editable = true, marker = "sys_platform == 'win32'" },
    ]
    # aeth-ext  = [
    #   { index = "SFTPyPI" },
    # ]
    poe-tasks = [
      { index = "SFTPyPI", marker = "sys_platform == 'linux'" },
      { path = "../poe_tasks", editable = true, marker = "sys_platform == 'win32'" },
    ]

  [[tool.uv.index]]
    name        = "SFTPyPI"
    url         = "https://pypi.sweetfiretobacco.com/jacob.ogden/internal/+simple"
    publish-url = "https://pypi.sweetfiretobacco.com/jacob.ogden/internal/"
    explicit    = true
